spring:
  application:
    name: payments
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://34.27.79.153:5432/empresas
    username: postgestsql
    password: jdk83dav
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.hibernate.SQL: debug